### ISSUE TITLE
Provide informations on uses (best practicies) with recommendations

### ISSUE THREAD

**Issue by zweiro** [MediaComem/bytesim-webapp#11]

**Comment by slecorne** [comment]
When clicking on the small 'i' icon a dialog should open with a best practice linked to the recommandation.
Recommandations will be taken from https://gr491.isit-europe.org/en/
Ex: recommandation image size-> best practices
* https://gr491.isit-europe.org/en/crit.php?id=9-5062-frontend-services-use-multiple-sizes-of-the-same
* https://gr491.isit-europe.org/en/crit.php?id=9-5061-frontend-digital-services-use-images-for-illustration-or
An initial version could be to list the title of best practice with the link to the website
@audreyhuguenin maybe our initial idea to integrate the content could be difficult because there may be multiple best practices per zone type

**Comment by MathildeIgier** [comment]
Need to have the mapping with all the titles and links associated to recommandations
What should we display if we have multiple links for one recommandation. Multiple icons ? One link with the root website page and all the titles in the tooltip ?
